# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: blender/ugrpc_pipe_blender.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class RenderRequest(betterproto.Message):
    scene_name: str = betterproto.string_field(1)
    camera_transformation: List[float] = betterproto.float_field(2)
    fov: float = betterproto.float_field(3)
    resolution: List[int] = betterproto.int32_field(4)
    vdb_path: str = betterproto.string_field(5)
    modality: str = betterproto.string_field(6)
    clip_range: List[float] = betterproto.float_field(7)


@dataclass(eq=False, repr=False)
class RenderReply(betterproto.Message):
    image_data: bytes = betterproto.bytes_field(1)
